## this is used by travis
homeassistant:
  name: Home Assistant
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: Europe/London

sensor:
  platform: ruter
  stopid: 2190400
  destination: 'Drammen'
  numer_of_departures: 3